image: node:18

stages:
  - build
  - test
  - publish

# Cache dependencies across jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Install dependencies
.setup:
  before_script:
    - npm ci

# Build the component library
build:
  extends: .setup
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

# Run any tests
test:
  extends: .setup
  stage: test
  script:
    - echo "Add test commands when you have tests"
  needs:
    - build

# Publish to GitLab's NPM Package Registry
publish:
  extends: .setup
  stage: publish
  script:
    # Publish the package
    - npm publish
  rules:
    # Only run on tags and when on default branch
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  needs:
    - build
    - test
